<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="MMin_To_Rpm_And_DegS" Id="{30ef750f-e3fd-4e06-a1c2-c66ec61ec0fd}" SpecialFunc="None">
    <Declaration><![CDATA[(* Convert meters per minute to degrees per second *)
FUNCTION MMin_To_Rpm_And_DegS : BOOL
VAR_INPUT
	MeterPerMinute 	: LREAL ; // Input meters per minute
	StitchLength	: LREAL ; // Input Stitch length
END_VAR
VAR_OUTPUT
	RevPerMinute	: LREAL ; // Output revolutions per minute
	DegPerSecond	: LREAL ; // Output degrees per second
END_VAR
VAR
	MmMin 	: LREAL ; // Millimeters per minute
	RevSec 	: LREAL ; // Millimeters per second
END_VAR	
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// ===== convert MMin to RPM =====
	RevPerMinute := (MeterPerMinute * 1000) / StitchLength ;
//===== Convert RPM to DegS =====
	DegPerSecond := (RevPerMinute/60)*360 ; 

	]]></ST>
    </Implementation>
    <LineIds Name="MMin_To_Rpm_And_DegS">
      <LineId Id="9" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="22" Count="2" />
      <LineId Id="21" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>