<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="Rpm_To_DegS" Id="{b6ed02a0-f0b4-4b90-a49f-32a1c9543fb2}" SpecialFunc="None">
    <Declaration><![CDATA[(* convert rotations per minute to degrees per second *)
FUNCTION Rpm_To_DegS : LREAL 
VAR_INPUT
	Rpm : LREAL ; // input revolutions per minute
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// ===== convert RPM to DegS ====
	Rpm_To_DegS := (Rpm/60)*360 ;
	]]></ST>
    </Implementation>
    <LineIds Name="Rpm_To_DegS">
      <LineId Id="9" Count="0" />
      <LineId Id="14" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>