<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="Between" Id="{636b1549-e7ce-4101-8455-6287d049e510}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Between : BOOL // Returns true if value is >= the lower and <= the upper threshold
VAR_INPUT
	Lower	: LREAL	; // lower threshold value [LREAL]
	Value	: LREAL	; // test value [LREAL]
	Upper	: LREAL	; // Upper threshold value [LREAL]
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Check if value is between lower and upper threshold
Between := (Value >= Lower) AND (Value <= Upper);]]></ST>
    </Implementation>
    <LineIds Name="Between">
      <LineId Id="18" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>