<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_LogHandlerBase" Id="{c49e850d-7280-093e-30c8-6ebb7bc3ee12}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'reflection'}
FUNCTION_BLOCK PUBLIC ABSTRACT FB_LogHandlerBase // Base class for all log handlers
VAR_OUTPUT
	{attribute 'instance-path'} 
    {attribute 'noinit'}
	sInstancePath : STRING; // Instance path of the function block
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_AddToLog" Id="{ebb0fcf3-f03d-0288-2f6b-00eb9ae0a605}">
      <Declaration><![CDATA[METHOD INTERNAL ABSTRACT M_AddToLog
VAR_INPUT
	sMsg : T_MaxString; // The message to be logged
	eLevel : E_LogLevel; // Log level (debug, info, warn, etc.)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>