<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PRG_TEST_FB_FAULTHANDLER" Id="{df25c322-66e9-42b5-bf1e-d85a6c4b3bb3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INTERNAL PRG_TEST_FB_FAULTHANDLER
VAR
	fbFaultHandler 	: FB_FaultHandler;
	stFault 		: UDT_Fault;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbFaultHandler();
fbFaultHandler.CmdAddFault(stFault);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>