<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PRG_TEST_FB_BASE" Id="{05d4333a-a3eb-08b5-275b-311b3bcb566f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INTERNAL PRG_TEST_FB_BASE
VAR
	bEnableTests : BOOL;
	fbBase : FB_Base_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF bEnableTests THEN
	fbBase.Init(1, 2, E_ComponentTypes.MainProgram);
	fbBase();
END_IF
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>