<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="DegS_To_Rpm_And_MMin" Id="{bc7c99b2-9596-4934-9eab-cd77a1bb192f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION DegS_To_Rpm_And_MMin : BOOL
VAR_INPUT
	DegPerSecond : LREAL ; // Input degrees per second
	StitchLength : LREAL ; // Input stitch length
END_VAR
VAR_OUTPUT
	RevPerMinute	: LREAL ; // Output revolutions per minute
	MetersPerMinute	: LREAL ; // Output meters per minute
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// ===== convert degrees per second to Rpm =====
	RevPerMinute := (DegPerSecond/360)*60 ;
// ===== Convert RPM to MMin =====
	MetersPerMinute := RevPerMinute * StitchLength / 1000 ;]]></ST>
    </Implementation>
    <LineIds Name="DegS_To_Rpm_And_MMin">
      <LineId Id="16" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>